# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-20 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='UniReview',
        ),
    ]
